[package]
name         = "hermes-tokio-runtime-components"
version      = { workspace = true }
edition      = { workspace = true }
license      = { workspace = true }
keywords     = { workspace = true }
repository   = { workspace = true }
authors      = { workspace = true }
rust-version = { workspace = true }
description  = """
    Modular runtime components implemented using Tokio
"""

[dependencies]
cgp                                 = { workspace = true }
hermes-runtime-components           = { workspace = true }
hermes-async-runtime-components     = { workspace = true }

tokio           = { workspace = true, features = ["full"] }
futures         = { workspace = true }
rand            = { workspace = true }
tracing         = { workspace = true }
tokio-stream    = { version = "0.1" }
