[package]
name         = "hermes-sovereign-client-components"
version      = { workspace = true }
edition      = { workspace = true }
license      = { workspace = true }
keywords     = { workspace = true }
repository   = { workspace = true }
authors      = { workspace = true }
rust-version = { workspace = true }
readme       = "README.md"
description  = """
    Context-generic client components for communicating with a Sovereign rollup node
"""

[dependencies]
ibc                                 = { workspace = true }
ibc-relayer                         = { workspace = true }
ibc-relayer-types                   = { workspace = true }
cgp-core                            = { workspace = true }
hermes-relayer-runtime              = { workspace = true }
hermes-relayer-components           = { workspace = true }
hermes-cosmos-client-components     = { workspace = true }
hermes-wasm-client-components       = { workspace = true }
hermes-cosmos-relayer               = { workspace = true }

ed25519-dalek   = { version = "2.1.0" }
eyre            = { workspace = true }
jsonrpsee       = { version = "0.21.0", features = ["http-client"] }