[package]
name         = "hermes-async-runtime-components"
version      = { workspace = true }
edition      = { workspace = true }
license      = { workspace = true }
keywords     = { workspace = true }
repository   = { workspace = true }
authors      = { workspace = true }
rust-version = { workspace = true }
readme       = "README.md"
description  = """
    Modular runtime components implemented using Tokio
"""

[dependencies]
hermes-relayer-components          = { workspace = true }
hermes-relayer-components-extra    = { workspace = true }
hermes-test-components             = { workspace = true }

cgp-core        = { workspace = true }
futures-core    = { workspace = true }
futures-util    = { workspace = true }
futures-channel = { workspace = true }

rand = { version = "0.8.5" }